### ISSUE TITLE
NXWitness 5.0.0.35745

### ISSUE THREAD

**Issue by rbrouwer** [ptr727/NxWitness#61]
According to the [release notes](https://www.networkoptix.com/all-nx-witness-release-notes) version 5.0.0.35745 was published 12 Oct 2022. Would it be possible to get builds for that newer version?

**Comment by ptr727** [comment]
Please see the [warning](https://github.com/ptr727/NxWitness#-warning) in the readme for why I am not currently auto updating builds.

I have been waiting for Nx to push 5.0 to release for DW Spectrum, but since it has been a long time and still not happened, I'll see if I can derive a different versioning strategy that does not break when Nx breaks the published releases versions.

**Comment by ptr727** [comment]
I changed the code to stop publishing `stable` tags, while resuming publishing current builds using the `latest` tag.
See: https://github.com/ptr727/NxWitness/issues/62
